# ============================================================
# Meta-Analysis R Script
# Generated by Agent 4: Statistical Analysis Agent
# Run in R 4.x with: install.packages(c("metafor", "ggplot2"))
# ============================================================

# ============================================================
# Meta-analysis R template - NOT RUNNABLE AS-IS
# BLOCKED: ai/n1/ci/n2 are null for all 3 studies (Navsaria2024, Lim2023, Wu2011).
# Fill in real event counts before running. Do not substitute placeholder numbers.
# ============================================================
library(metafor)
library(meta)

# --- 1. Data entry (REPLACE NA with actual extracted counts) ---
dat <- data.frame(
  study        = c("Navsaria2024", "Lim2023", "Wu2011"),
  ai           = c(NA, NA, NA),   # intervention/exposed events
  n1i          = c(NA, NA, NA),   # intervention/exposed total N
  ci           = c(NA, NA, NA),   # control/unexposed events
  n2i          = c(NA, NA, NA),   # control/unexposed total N
  design       = c("cohort", "cohort", "cross-sectional"),
  follow_up_wk = c(NA, NA, NA)
)

stopifnot(!anyNA(dat[, c("ai","n1i","ci","n2i")]))  # fails until data is supplied

# --- 2. Effect size calculation ---
# OR is generally preferred for cohort/case-control designs; if all studies
# report prevalence/risk directly and follow-up is comparable, RR is more
# interpretable. Re-evaluate once design/outcome details are confirmed --
# note Wu2011 is cross-sectional, which may not be poolable with the two
# cohort studies without an RR/OR sensitivity check (see below).
dat <- escalc(measure = "OR", ai = ai, n1i = n1i, ci = ci, n2i = n2i, data = dat, slab = study)

# --- 3. Pooling model ---
# With k = 3, a random-effects (REML) model with Knapp-Hartung adjustment
# is used by default per protocol; heterogeneity will determine whether
# fixed-effect is defensible instead. With so few studies, I^2 estimates
# are unstable and should be interpreted cautiously.
res <- rma(yi, vi, data = dat, method = "REML", test = "knha")
print(res)

# --- 4. Heterogeneity ---
cat(sprintf("I^2 = %.1f%%, tau^2 = %.4f, Q(df=%d) = %.2f, p = %.4f\n",
            res$I2, res$tau2, res$k - 1, res$QE, res$QEp))

# --- 5. Forest plot with prediction interval ---
pred <- predict(res)
forest(res, addpred = TRUE, header = TRUE,
       xlab = "Odds Ratio",
       mlab = "RE Model (REML, HKSJ)")

# --- 6. Subgroup analysis: design ---
# k=3 with a 2/1 split across subgroups is too small for a meaningful
# formal moderator test; report descriptively only.
res_design <- rma(yi, vi, mods = ~ design, data = dat, method = "REML", test = "knha")
print(res_design)

# --- 6b. Subgroup analysis: follow_up_wk ---
# follow_up_wk is null for all studies; cannot be modeled until supplied.
# res_followup <- rma(yi, vi, mods = ~ follow_up_wk, data = dat, method = "REML", test = "knha")

# --- 7. Leave-one-out sensitivity analysis ---
loo <- leave1out(res)
print(loo)

# --- 7b. Sensitivity: high-ROB excluded ---
# Requires a risk-of-bias column (e.g., dat$rob) not present in the supplied
# data; add ROB ratings per study before running.
# res_lowrob <- rma(yi, vi, data = subset(dat, rob != "high"), method = "REML", test = "knha")

# --- 7c. Sensitivity: RCT only ---
# No study in this set has design == "RCT" (2 cohort, 1 cross-sectional),
# so this sensitivity scenario is not applicable to the current study set.
# res_rct <- rma(yi, vi, data = subset(dat, design == "RCT"), method = "REML", test = "knha")

# --- 8. Publication bias ---
# NOTE: Egger's test and trim-and-fill are statistically underpowered/
# not recommended with k < 10 studies (Egger's test requires >=10 for
# reliable power per Cochrane Handbook Ch.13); reported here for
# completeness only, and should NOT be over-interpreted for k=3.
egger <- regtest(res, model = "lm")
print(egger)

tf <- trimfill(res)
print(tf)

funnel(res, main = "Funnel Plot")
