# Auto-generated by Agent 3: Data Extraction
library(metafor)

dat <- data.frame(
  list(study="Navsaria2024", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Lim2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Wu2011", ai=None, n1i=None, ci=None, n2i=None)
)

# Convert to proper format
dat <- do.call(rbind, lapply(dat, as.data.frame))