# Auto-generated by Agent 3: Data Extraction
library(metafor)

dat <- data.frame(
  list(study="Chang2025", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Akgun2025", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Asare2025", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Aristizabal2025", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Nadelmann2025", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Dhaliwal2025", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Rypka2024", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Lin2024", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Navsaria2024", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Lin2024", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Joshi2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Lim2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Holman2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Fernandez2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Brunsgaard2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Brunsgaard2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Munjal2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Fernandez2023", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Raval2022", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Lam2022", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Zakhem2022", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Brady2021", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Paul2024", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Hogue2019", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Wang2016", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Baldwin2016", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Clairwood2014", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Agbai2014", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Feng2013", ai=None, n1i=None, ci=None, n2i=None),
  list(study="PharmD2013", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Wu2011", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Ekwueme2011", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Chi2011", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Hu2009", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Cormier2006", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Murase2005", ai=None, n1i=None, ci=None, n2i=None),
  list(study="Halder2003", ai=None, n1i=None, ci=None, n2i=None)
)

# Convert to proper format
dat <- do.call(rbind, lapply(dat, as.data.frame))